#pragma once

#define AXIS_VERSION_MAJOR 1
#define AXIS_VERSION_MINOR 1
#define AXIS_VERSION_PATCH 0

#define AXIS_VERSION_STR  "1.1.0"
#define AXIS_BUILD_DATE   __DATE__
#define AXIS_BUILD_TIME   __TIME__

#define AXIS_VERSION_FULL AXIS_VERSION_STR " (" AXIS_BUILD_DATE " " AXIS_BUILD_TIME ")"
#define AXIS_USER_AGENT   "Axis/" AXIS_VERSION_STR
